# https://github.com/DavidAnson/markdownlint-cli2/blob/main/test/markdownlint-cli2-yaml-example/.markdownlint-cli2.yaml

config:
  default: true
  first-line-h1: false
  first-header-h1: false
  line_length: false
  no-multiple-blanks: false
  no-inline-html: true
  no-alt-text: false
  heading-increment: false

# Ignore files referenced by .gitignore (only valid at root)
gitignore: true

# Fix any fixable errors
fix: false
